cache for states
hyperledger-labs/orion-server pull request #473
Opened 2022-12-12 10:01 UTC by cendhu

Signed-off-by: senthil <cendhu@gmail.com>

2022-12-14 11:27 UTC, liran-funaro requested changes

2022-12-14 11:27 UTC, liran-funaro commented on internal/worldstate/leveldb/cache.go
> +		fmt.Println(namespace, key)
Please remove debugging code.

2023-01-05 08:28 UTC, cendhu commented on internal/worldstate/leveldb/cache.go
> +	c.dataCache.Set(cacheKey, cacheValue)
When the length of the value cannot be encoded within 2 bytes or does not fit into a chunk, the value is not updated. Hence, we always delete before updating the value. We have a similar logic in fabric too while using this cache library - https://github.com/hyperledger/fabric/blob/main/core/ledger/kvledger/txmgmt/statedb/statecouchdb/cache.go

2023-01-05 08:28 UTC, cendhu commented on internal/worldstate/leveldb/cache.go
> +		fmt.Println(namespace, key)
Done

2023-01-05 08:28 UTC, cendhu commented on internal/worldstate/leveldb/cache.go
> +		c.dataCache.Set(cacheKey, cacheValue)
Due to value size limit.

2023-01-09 13:46 UTC, liran-funaro commented on internal/worldstate/leveldb/cache.go
> +	c.dataCache.Set(cacheKey, cacheValue)
Can you please add a comment explaining this?

2023-01-23 10:22 UTC, liran-funaro commented on internal/worldstate/leveldb/cache.go
> +	c.dataCache.Set(cacheKey, cacheValue)
Please address this.

2023-01-23 14:07 UTC, merged